"""att artigo

Revision ID: 08bbc8f9ebb5
Revises: 8f22aaebe5ec
Create Date: 2025-10-04 12:13:31.792076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bbc8f9ebb5'
down_revision: Union[str, None] = '8f22aaebe5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('id_edicao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'id_edicao')
    # ### end Alembic commands ###
