"""add autor em artigo

Revision ID: 0c0e74ba4e11
Revises: 4c208f1a861c
Create Date: 2025-09-17 12:34:17.351878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0e74ba4e11'
down_revision: Union[str, None] = '4c208f1a861c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('autor', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'autor')
    # ### end Alembic commands ###
