"""remover autores em artigo

Revision ID: 4c208f1a861c
Revises: ba2f48e32eb7
Create Date: 2025-09-17 12:27:30.895259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c208f1a861c'
down_revision: Union[str, None] = 'ba2f48e32eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'autores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('autores', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
