"""entidade promotora em evento

Revision ID: 4fd459e5c66f
Revises: 5f19db4f795d
Create Date: 2025-10-04 11:05:09.183989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd459e5c66f'
down_revision: Union[str, None] = '5f19db4f795d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('entidade_promotora', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'entidade_promotora')
    # ### end Alembic commands ###
