"""remove rotas em auth

Revision ID: 5f19db4f795d
Revises: 43698b23f3cf
Create Date: 2025-10-04 10:54:07.321012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f19db4f795d'
down_revision: Union[str, None] = '43698b23f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'notify')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('notify', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
