"""add book, publisher, loc em artigos

Revision ID: 8f22aaebe5ec
Revises: 9ce739301eb8
Create Date: 2025-10-04 11:55:39.452883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f22aaebe5ec'
down_revision: Union[str, None] = '9ce739301eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('booktitle', sa.String(), nullable=True))
    op.add_column('artigos', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('artigos', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'location')
    op.drop_column('artigos', 'publisher')
    op.drop_column('artigos', 'booktitle')
    # ### end Alembic commands ###
