"""class artigo modificada

Revision ID: 9ce739301eb8
Revises: 4fd459e5c66f
Create Date: 2025-10-04 11:43:17.402688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce739301eb8'
down_revision: Union[str, None] = '4fd459e5c66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artigos_doi'), table_name='artigos')
    op.drop_column('artigos', 'paginas')
    op.drop_column('artigos', 'autor')
    op.drop_column('artigos', 'id_edicao')
    op.drop_column('artigos', 'doi')
    op.drop_column('artigos', 'numero')
    op.drop_column('artigos', 'volume')
    op.drop_column('artigos', 'journal')
    op.drop_column('artigos', 'publicador')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('publicador', sa.VARCHAR(), nullable=True))
    op.add_column('artigos', sa.Column('journal', sa.VARCHAR(), nullable=True))
    op.add_column('artigos', sa.Column('volume', sa.VARCHAR(), nullable=True))
    op.add_column('artigos', sa.Column('numero', sa.VARCHAR(), nullable=True))
    op.add_column('artigos', sa.Column('doi', sa.VARCHAR(), nullable=True))
    op.add_column('artigos', sa.Column('id_edicao', sa.INTEGER(), nullable=False))
    op.add_column('artigos', sa.Column('autor', sa.VARCHAR(), nullable=False))
    op.add_column('artigos', sa.Column('paginas', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_artigos_doi'), 'artigos', ['doi'], unique=1)
    # ### end Alembic commands ###
