"""add table Evento

Revision ID: ae414f8015fa
Revises: 41d392c43f54
Create Date: 2025-09-02 00:26:48.742314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae414f8015fa'
down_revision: Union[str, None] = '41d392c43f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('site', sa.String(), nullable=True))
    op.drop_column('eventos', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.drop_column('eventos', 'site')
    # ### end Alembic commands ###
