"""add autor em Artigo

Revision ID: ba2f48e32eb7
Revises: a0c4c04f3d7f
Create Date: 2025-09-17 12:15:10.146686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2f48e32eb7'
down_revision: Union[str, None] = 'a0c4c04f3d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigos', sa.Column('autores', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artigos', 'autores')
    # ### end Alembic commands ###
