"""artigos table

Revision ID: f8bb0703706d
Revises: 6b94b88d6283
Create Date: 2025-09-03 15:15:30.944889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bb0703706d'
down_revision: Union[str, None] = '6b94b88d6283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('caminho_pdf', sa.String(), nullable=True),
    sa.Column('id_edicao', sa.Integer(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('paginas', sa.String(), nullable=True),
    sa.Column('publicador', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artigos_doi'), 'artigos', ['doi'], unique=True)
    op.create_index(op.f('ix_artigos_id'), 'artigos', ['id'], unique=False)
    op.create_index(op.f('ix_artigos_titulo'), 'artigos', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artigos_titulo'), table_name='artigos')
    op.drop_index(op.f('ix_artigos_id'), table_name='artigos')
    op.drop_index(op.f('ix_artigos_doi'), table_name='artigos')
    op.drop_table('artigos')
    # ### end Alembic commands ###
